In [7]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(list(map(lambda x : x ** 2 , numbers)))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [8]:
squared = [i ** 2 for i in numbers]
print(squared)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [14]:
odd = [num ** 2 for num in numbers if num % 2 == 1]
print(odd)

[1, 9, 25, 49, 81]


In [18]:
List = [5, 10, 15, 20, 25, 30]
print(list(map(lambda x : x % 5, List)))

[0, 0, 0, 0, 0, 0]


In [26]:
bers = []
for i in range (1, 11):
    bers.append(i)
mul3 = [um for um in bers if um % 3 == 0]
print(mul3)

[3, 6, 9]


In [ ]:
tuple = [(1,2), (3,4), (5,6)]
sum = list(map(lambda x : x[0]+ x[1], tuple))
print(sum)

[3, 7, 11]


In [60]:
fruits = ['apple', 'banana', 'cherry']
length = list(map(lambda le : len(le), fruits))
print(length)

[5, 6, 6]


In [66]:
li = [3, 6, 9, 12, 15]
total = list(map(lambda x : x * 2, li))

In [67]:
print(total)

[6, 12, 18, 24, 30]


In [92]:
import numpy as np
zeros_arr = np.zeros((2,3))
print(zeros_arr)

ones_arr = np.ones((2,3))
print(ones_arr)

full_arr = np.full((2,3),8)
print(full_arr)

arr = np.arange(1, 15, 3)
result = arr // 2
print(arr)
print(result)

arr1 = np.linspace(1, 2, 10)
print(arr1)

arr_random = np.random.rand(4, 5)
print(arr_random)
print(arr_random * 100)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[8 8 8]
 [8 8 8]]
[ 1  4  7 10 13]
[0 2 3 5 6]
[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]
[[0.98348982 0.16802485 0.63706627 0.29852152 0.37200043]
 [0.95497754 0.52848283 0.10103069 0.32879118 0.27448986]
 [0.43200009 0.91792828 0.31456563 0.65719173 0.68265886]
 [0.46179155 0.18040837 0.07268439 0.29630056 0.13588575]]
[[98.34898205 16.8024852  63.70662671 29.85215168 37.20004295]
 [95.49775431 52.84828289 10.10306935 32.87911824 27.44898611]
 [43.20000944 91.79282843 31.456563   65.71917343 68.2658861 ]
 [46.17915476 18.04083719  7.26843881 29.63005553 13.58857531]]


In [108]:
arr1 = np.array([1, 4, 7])
arr2 = np.array([0, 3, 6])
print(arr1-arr2)

arr3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = arr3 ** 3
print(result)

row_sum = np.sum(arr3, axis = 1)
col_sum = np.sum(arr3, axis = 0)

print(row_sum)
print(col_sum)

[1 1 1]
[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]
[ 6 15 24]
[12 15 18]


In [121]:
np.random.seed(42)
arr5 = np.random.randint(0, 16, (4, 4))
print(arr5 % 2 == 0)
print(arr5)

[[ True False  True  True]
 [ True False  True  True]
 [ True False  True  True]
 [ True  True False  True]]
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]
