In [2]:
import numpy as np

In [9]:
#문제 1.
# 1~12까지 숫자를 포함한 배열을 만들고, 이를 3행 4열로 reshape 하시오.
# 그리고 두 번째 열만 추출하시오.
arr = np.arange(1, 13)
print(arr)
arr = arr.reshape(3,4)
print("\n", arr)
print("\n", arr[:,1])

[ 1  2  3  4  5  6  7  8  9 10 11 12]

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 [ 2  6 10]


In [16]:
# 문제 2.
# 다음 배열에서 값이 10 이상인 값만 True, 나머지는 False인 불리언 배열을 만드시오

arr = np.array([[5, 10, 15], [3, 7, 12]])
print(arr)
print("\n", arr >= 10)

[[ 5 10 15]
 [ 3  7 12]]

 [[False  True  True]
 [False False  True]]


In [30]:
# 문제 3.
# 다음 배열에서 각 행의 최대값을 구하시오.

arr = np.array([[1, 4, 2], [7, 0, 9]])
print(arr)
print("\n", np.max(arr[0]), np.max(arr[1]))

[[1 4 2]
 [7 0 9]]

 4 9


In [48]:
# 문제 4.
# np.random.seed(0)을 고정한 후, 정수 0~99 중 5행 2열의 랜덤 배열을 만들고, 각 열의 평균을 구하시오.

a = np.random.seed(0)
a = np.random.randint(0,100, (5,2))
print(a)
print("\n", np.sum(a[:, 0]), np.sum(a[:, 1]))
print("\n", np.average(a[:, 0]), np.average(a[:, 1]))

[[44 47]
 [64 67]
 [67  9]
 [83 21]
 [36 87]]

 294 231

 58.8 46.2


In [56]:
# 문제 5.
# 다음 문자열 배열에서 각 원소의 길이를 구하시오.

arr = np.array(['apple', 'banana', 'cherry'])
for i in range (len(arr)):
    print(len(arr[i]))

5
6
6


In [87]:
# 문제 6.
# 다음 배열의 짝수는 그대로 두고, 홀수는 -1로 바꾸는 배열을 만드시오.
# np.where 사용
arr = np.array([1, 2, 3, 4, 5, 6]) 
arr = np.where(arr % 2 == 0, arr, -1)
print(arr)

[-1  2 -1  4 -1  6]


In [64]:
# 문제 7.
# 3차원 배열 arr이 다음과 같을 때, 각 2차원 행렬(면)의 첫 번째 행의 평균을 구하시오.

arr = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(np.average(arr[0][0,:]))

2.0


In [110]:
# 문제 8.
# 임의의 (5, 4) 배열을 생성한 뒤, 열 별로 가장 큰 값을 100으로 바꾸는 코드를 작성하시오.
# (단, 같은 값이 여러 개일 경우 전부 바뀜)
arr = np.random.randint(0,20, (5,4))
print(arr)
for i in range (len(arr)):
    arr[arr == np.max(arr[i])] = 100
print("\n", arr)

[[ 3  6  3  6]
 [19  2 18 18]
 [ 6 11  0  4]
 [13  9  2  1]
 [12 15  1 12]]

 [[  3 100   3 100]
 [100   2  18  18]
 [100  11   0   4]
 [100   9   2   1]
 [ 12 100   1  12]]


In [115]:
# 문제 9.
# 다음 2차원 배열에서 각 열(column)별로 최소값이 있는 인덱스를 구하시오.
# argmin() 함수를 사용하시오.
arr = np.array([[12, 15, 10],[5, 7, 9],[3, 4, 6]])
print(np.argmin(arr, axis=0))

[2 2 2]


In [150]:
# 문제 10.
# 다음과 같은 2차원 배열이 있을 때,
# **행(row)과 열(column)을 교환(transpose)**한 후, 첫 번째 열을 제외하고 나머지 열을 1로 초기화하시오.
arr = np.array([[2, 3, 4],
                [5, 6, 7],
                [8, 9, 10]])
arr = np.transpose(arr)
arr[:,1:] = True
print(arr)

[[2 1 1]
 [3 1 1]
 [4 1 1]]


# 강의자료

In [180]:
# 2-3-4
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90], [100, 110, 120]])
print(arr)

index = np.argwhere(np.char.startswith(arr.astype(str), '1'))
print("\n", index)

for i in index:
    arr[tuple(i)] = 0
print("\n", arr)



[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]

 [[0 0]
 [3 0]
 [3 1]
 [3 2]]

 [[ 0 20 30]
 [40 50 60]
 [70 80 90]
 [ 0  0  0]]


In [181]:
# 2-3-5
for i in range (6):
    a5rr = np.arange(5*i)
a6rr = a5rr.reshape(5,5)
a6rr[0, :] = 0
print(a6rr)

[[ 0  0  0  0  0]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
